trigger:
- main
  
variables:
  - group: 'LogicAppDemo'
  - name: templateFile
    value: 'Infrastructure/main-vnet.bicep'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters virtualNetworkName=$(virtualNetworkName) > outputs.json