trigger: none

variables:
  - group: 'LogicAppDemo1'
  - name: artifactName
    value: 'LA.zip'

stages:
- template: ci-stage-template.yml
  parameters:
    stageName: 'BuildArtifacts'
    stageDisplayName: 'Build Artifacts'
    artifactName: $(artifactName)

- template: cd-stage-template.yml
  parameters:
    stageName: 'DeployDEV'
    stageDisplayName: 'Deploy App DEV'
    variableGroupName: 'LogicAppDemo-Dev1'
    resourceGroupName: $(resourceGroupNameDev)
    environment: 'DEV'
    triggerFrequency: 'Minute'
    artifactName: $(artifactName)

- template: cd-stage-template.yml
  parameters:
    stageName: 'DeployQA'
    stageDisplayName: 'Deploy App QA'
    variableGroupName: 'LogicAppDemo-QA1'
    resourceGroupName: $(resourceGroupNameQA)
    environment: 'QA'
    triggerFrequency: 'Day'
    artifactName: $(artifactName)
