# ----------------------------------------------------------------------------------------------------
# Template to Deploy Azure resources
# ----------------------------------------------------------------------------------------------------
parameters: 
  environment: ''
  azureSubscription: ''

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: DeployResources
  displayName: Initialize Deploy Resources
  environment: ${{ parameters.environment }}

- job: DeployResourcesJob
  displayName: Deploy Resources
  variables:
  - name: environment
    value: ${{ parameters.environment }}
  - name: environmentLower
    value: ${{ lower(parameters.environment) }}
  - name: appPrefixLower
    value: ${{ lower(variables.appPrefix) }}
  - name: templateFile
    value: '$(Pipeline.Workspace)/s/Infrastructure/bicep/main.bicep'

  steps:
  - bash: |
      resourceGroupName=$(echo "rg_$(appPrefixLower)_logic_app" | tr '[:upper:]' '[:lower:]' | tr '-' '_')
      echo "##vso[task.setvariable variable=resourceGroupName]$resourceGroupName"
    displayName: 'Create Variables'

  - bash: |
      echo "azureSubscription=$(azureSubscription)"
      echo "resourceGroupName=$(resourceGroupName)"
      echo "region=$(region)"
      echo "environment=$(environment)"
      echo "environmentLower=$(environmentLower)"
      echo "appPrefix=$(appPrefix)"
      echo "appPrefixLower=$(appPrefixLower)"
      echo "templateFile=$(templateFile)"
      tree $(Pipeline.Workspace)
    displayName: 'Display Variables'
    continueOnError: true

  - task: AzureCLI@2
    displayName: 'Create Resource Group'
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: az group create --name $(resourceGroupName) --location $(region)

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Publish Bicep Resources'
    inputs:
      csmFile: $(templateFile)
      overrideParameters: >
        -appPrefix $(appPrefix) 
        -environment 'dev'
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: $(azureSubscription)
      resourceGroupName: '$(resourceGroupName)'
      location: '$(region)'
      action: 'Create Or Update Resource Group'
      templateLocation: 'Linked artifact'
      deploymentMode: 'Incremental'
      continueOnError: ignoreError
