# ----------------------------------------------------------------------------------------------------
# Template to deploy a logic app standard to a Function App
# ----------------------------------------------------------------------------------------------------
parameters: 
  azureSubscription: ''
  triggerFrequency: ''

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: LogicAppDeploy
  displayName: Deploy Logic App
  environment: 'DEV'

  variables:
  - name: stageName
    value: ${{ parameters.stageName }}
  - name: triggerFrequency
    value: ${{ parameters.triggerFrequency }}
  - name: artifactFolderName
    value: 'App'
  - name: artifactName
    value: 'LA.zip'

  strategy:
    runOnce:
      deploy:
        steps:
        - bash: |
            logic_app_name=$(echo "$(appPrefix)-demo-logic-app" | tr '[:upper:]' '[:lower:]')
            echo "##vso[task.setvariable variable=logic_app_name]$logic_app_name"

            resourceGroupName=$(echo "rg_$(appPrefixLower)_logic_app" | tr '[:upper:]' '[:lower:]')
            echo "##vso[task.setvariable variable=resource_group_name]$resource_group_name"
          displayName: 'Create Variables'

        - bash: |
            echo "resource_group_name=$(resource_group_name)"
            echo "logic_app_name=$(logic_app_name)"
            echo "azureSubscription=$(azureSubscription)"
            echo "region=$(region)"
            echo "appPrefix=$(appPrefix)"
            echo "triggerFrequency=$(triggerFrequency)"
            echo "Pipeline.Workspace=$(Pipeline.Workspace)"
            tree $(Pipeline.Workspace)
          displayName: 'Display Variables'
          continueOnError: true

        - task: AzureFunctionApp@1
          displayName: 'Deploy Logic App Zip'
          retryCountOnTaskFailure: 2
          inputs:
            azureSubscription: $(azureSubscription)
            appType: 'functionApp'
            appName: $(logic_app_name)
            package: '$(Pipeline.Workspace)/$(artifactFolderName)/$(artifactName)'
            deploymentMethod: 'zipDeploy'
            AppSettings: '-TRIGGER_FREQUENCY $(triggerFrequency)'