# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Azure Resources for All Environments
# ------------------------------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group "LogicAppDemo-<env>" -> one for EACH environment being deployed.
#  See ../Docs/VariableGroups.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: 'ubuntu-latest'

# ----------------------------------------------------------------------------------------------------
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Infrastructure/*

# ----------------------------------------------------------------------------------------------------
stages:
  - stage: DeployDEVResources
    displayName: DEV Deploy Resources
    jobs:
    - template: azure-release-stage-template2.yml
      parameters:
        environment: 'DEV'
        variableGroupName: 'LogicAppDemo-Dev1'
        templateFile: '$(Pipeline.Workspace)/Infrastructure/main.bicep'

  - stage: DeployQAResources
    displayName: QA Deploy Resources
    jobs:
    - template: azure-release-stage-template2.yml
      parameters:
        environment: 'QA'
        variableGroupName: 'LogicAppDemo-QA1'
        templateFile: '$(Pipeline.Workspace)/Infrastructure/main.bicep'
