trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-logic-app.1.Build-Infra-Templates'

variables:
  - group: 'LogicAppDemo'
  - name: templateFile
    value: '$(Pipeline.Workspace)/build/Infrastructure/main.bicep'

pool:
  vmImage: 'ubuntu-latest'

stages:
- template: azure-release-stage-template.yml
  parameters:
    stageName: 'INFRADEV'
    stageDisplayName: 'Create Infra DEV'
    environment: 'DEV'
    resourceGroupName: $(resourceGroupNameDev)

- template: azure-release-stage-template.yml
  parameters:
    stageName: 'INFRAQA'
    stageDisplayName: 'Create Infra QA'
    environment: 'QA'
    resourceGroupName: $(resourceGroupNameQA)
