# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to scan existing Logic Application and pull down changes to the repository
# This pipeline needs variable group LogicAppRefresh
# See docs/Create-Refresh-Variable-Group.md for details on how to create this.
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: windows-latest

# ----------------------------------------------------------------------------------------------------
trigger:
  - none

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: InitializeRefreshWorkflowRepo
  displayName: Initialize Refresh Workflow Repo
  environment: 'DEV'

- job: RefreshWorkflowsRepo
  displayName: Refresh Workflow Repo
  variables:
    - group: LogicAppRefresh

  steps:
  - bash: |
      runDateTime=$(echo "$(date '+%Y-%m-%d_%H-%M-%S')")
      echo "##vso[task.setvariable variable=runDateTime]$runDateTime"
      echo "runDateTime=$runDateTime"

      branchName=$(echo "refresh_branch_$runDateTime")
      echo "##vso[task.setvariable variable=branchName]$branchName"
      echo "branchName=$branchName"

      commitMessage=$(echo "Refresh Workflow via Pipeline on $runDateTime")
      echo "##vso[task.setvariable variable=commitMessage]$commitMessage"
      echo "commitMessage=$commitMessage"
    displayName: 'Create Variables'

  - bash: |
      echo "runDateTime=$(runDateTime)"
      echo "branchName=$(branchName)"
      echo "commitMessage=$(commitMessage)"
      echo "resourceGroupName=$(resourceGroupName)"
      echo "logicAppName=$(logicAppName)"
    displayName: 'Display Variables'
    continueOnError: true

  # Check out the repository
  - checkout: self
    persistCredentials: true

  # Login is needed in order to scan the existing workflows
  - script: az login --service-principal -u $(principalId) -p $(clientSecret) --tenant $(tenantId)
    displayName: 'Login to Azure'

  # Go pull down the latest repo and create a branch
  - script: |
      git config --global user.email pipeline@demo.com & git config --global user.name "Pipeline"
      git checkout -b $(branchName)
      git push --set-upstream origin $(branchName)
      git pull origin $(branchName)
    displayName: Fetch Source Repo
    workingDirectory: $(System.DefaultWorkingDirectory)

  # Go scan the workflows in the portal for changes
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: '$(System.DefaultWorkingDirectory)\Infrastructure\scripts\download-portal-workflows.ps1'
      arguments: '-resourceGroupName $(resourceGroupName) -logicAppName $(logicAppName)'
    displayName: Download Workflows

  # Add our changes to a commit and check it in
  - script: |
      git add .
      git commit -m "$(commitMessage)"
      git push origin $(branchName)
    displayName: Update Source Repo
    workingDirectory: $(System.DefaultWorkingDirectory)
