# ----------------------------------------------------------------------------------------------------
# Template to create Azure resources
# ----------------------------------------------------------------------------------------------------
parameters: 
  variableGroupName:  'myVariableGroup'
  environment:  'DEV'
  azureSubscription: ''

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: CreateInfra
  displayName: Initialize Create Infra
  environment: ${{ parameters.environment }}

- job: CreateInfraJob
  displayName: Create Infrastructure
  variables:
  - group: ${{ parameters.variableGroupName }}
  - name: environment
    value: ${{ parameters.environment }}
  - name: environmentLower
    value: ${{ lower(parameters.environment) }}
  - name: templateFile
    value: '$(Pipeline.Workspace)/s/Infrastructure/bicep/main.bicep'

  steps:
  - bash: |
      echo "azureSubscription=$(azureSubscription)"
      echo "resourceGroupName=$(resourceGroupName)"
      echo "region=$(region)"
      echo "environment=$(environment)"
      echo "environmentLower=$(environmentLower)"
      echo "appPrefix=$(appPrefix)"
      echo "templateFile=$(templateFile)"
      tree $(Pipeline.Workspace)
    displayName: 'Display Variables'
    continueOnError: true

  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        ls
        az group create --name $(resourceGroupName) --location $(region)
        az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters appPrefix=$(appPrefix) environment=$(environmentLower) blobStorageContributorId=$(blobStorageContributorId) > outputs.json
