parameters: 
- name: variableGroupName
  default: 'LogicAppDemoDev'
- name: resourceGroupName
  default: ''
- name: stageName
  default: ''
- name: stageDisplayName
  default: ''
- name: environment
  default: ''
- name: triggerFrequency
  default: ''
- name: artifactName
  default: 'LA.zip'

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageDisplayName }}

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: ${{ parameters.environment }}
      pool:
        vmImage: 'ubuntu-latest'
  
      variables:
      - group: ${{ parameters.variableGroupName }}
      - name: resourceGroupName
        value: ${{ parameters.resourceGroupName }}        
      - name: stageName
        value: ${{ parameters.stageName }}
      - name: environment
        value: ${{ parameters.environment }}
      - name: triggerFrequency
        value: ${{ parameters.triggerFrequency }}

      strategy:
        runOnce:
          deploy:
            steps:
            - bash: |
                echo "azureSubscription=$(azureSubscription)"
                echo "azureSubscriptionId=$(azureSubscriptionId)"
                echo "region=$(region)"
                echo "resourceGroupName=$(resourceGroupName)"
                echo "environment=$(environment)"
                echo "appPrefix=$(appPrefix)"
                echo "logicAppName=$(logicAppName)"
                echo "storageAccountName=$(storageAccountName)"
                echo "triggerFrequency=$(triggerFrequency)"
                echo "Pipeline.Workspace=$(Pipeline.Workspace)"
                tree $(Pipeline.Workspace)
              displayName: 'Display Variables'
              continueOnError: true

            - task: AzureFunctionApp@1
              displayName: 'Deploy logic app workflows'
              inputs:
                azureSubscription: $(azureSubscription)
                appType: 'functionApp'
                appName: $(logicAppName)
                package: '$(Pipeline.Workspace)/App/$(artifactName)'
                deploymentMethod: 'zipDeploy'
                AppSettings: '-WORKFLOWS_SUBSCRIPTION_ID $(azureSubscriptionId) -WORKFLOWS_LOCATION_NAME $(region) -WORKFLOWS_RESOURCE_GROUP_NAME $(resourceGroupName) -STORAGE_ACCOUNT_NAME  $(storageAccountName) -TRIGGER_FREQUENCY $(triggerFrequency)'